# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 555a7148d748b0c96472e7020abb387444f6efda05df06aac8c65448c8ad2e0e599427905543bd985579d4fb5d71c5d32b357d84efc6dba4d63886e3f754e209

test:
  secret_key_base: 5034e770ee6eee9dcd82f4cfd41687a2bed60aa52ae80daae5bcffd3f2cdb9d16474d14dc6264cf4011a6742a34ce5863dc5fab06c73abdce6eab162ea8444f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
